const video=document.getElementById("video"),overlay=document.getElementById("overlay"),ctx=overlay.getContext("2d"),statusEl=document.getElementById("status"),aiStatusEl=document.getElementById("aiStatus"),guideEl=document.getElementById("guide"),debugEl=document.getElementById("debug"),startBtn=document.getElementById("startBtn"),shotBtn=document.getElementById("shotBtn"),switchBtn=document.getElementById("switchBtn");
let stream=null,facingMode="environment",detector=null,running=false,aiLoading=false,lastInference=0,lastGuide="";
function guide(t){if(t!==lastGuide){guideEl.textContent=t;lastGuide=t}}
function resize(){overlay.width=video.videoWidth||innerWidth;overlay.height=video.videoHeight||innerHeight}
video.addEventListener("loadedmetadata",resize);addEventListener("resize",resize);
async function startCamera(){try{if(!isSecureContext)throw Error("不是安全連線（HTTPS）");if(!navigator.mediaDevices?.getUserMedia)throw Error("此瀏覽器不支援相機");if(stream)stream.getTracks().forEach(t=>t.stop());stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facingMode},width:{ideal:1280},height:{ideal:720}},audio:false});video.srcObject=stream;video.muted=true;video.playsInline=true;await video.play();resize();statusEl.textContent="相機已開啟";shotBtn.disabled=false;startBtn.textContent="重新啟動";guide("AI 準備中…");startLoop();loadAI()}catch(e){statusEl.textContent="相機無法開啟";guide("請允許 Safari 使用相機");debugEl.textContent=(e.name||"Error")+"："+(e.message||e)}}
async function loadAI(){if(aiLoading||detector)return;aiLoading=true;aiStatusEl.textContent="AI：載入中…";debugEl.textContent="AI ① TensorFlow.js";try{if(!window.tf)throw Error("TensorFlow.js 未載入");await tf.ready();debugEl.textContent="AI ② TFJS "+tf.version.tfjs;if(!window.poseDetection)throw Error("Pose Detection 未載入");debugEl.textContent="AI ③ MoveNet 模型載入中…";detector=await poseDetection.createDetector(poseDetection.SupportedModels.MoveNet,{modelType:poseDetection.movenet.modelType.SINGLEPOSE_LIGHTNING,enableSmoothing:true});aiStatusEl.textContent="AI：已就緒";debugEl.textContent="AI ④ 人體即時偵測已啟動";guide("請讓人物進入畫面")}catch(e){detector=null;aiStatusEl.textContent="AI：載入失敗";debugEl.textContent=(e.name||"Error")+"："+(e.message||e);guide("AI 尚未就緒，但相機可使用")}finally{aiLoading=false}}
function startLoop(){if(running)return;running=true;requestAnimationFrame(loop)}
async function loop(now){if(!running)return;if(detector&&video.readyState>=2&&now-lastInference>100){lastInference=now;try{const p=await detector.estimatePoses(video,{flipHorizontal:false});draw(p?.[0])}catch(e){debugEl.textContent="偵測錯誤："+(e.message||e)}}requestAnimationFrame(loop)}
function draw(p){ctx.clearRect(0,0,overlay.width,overlay.height);if(!p?.keypoints){guide("請讓人物進入畫面");return}const k=p.keypoints.filter(x=>(x.score||0)>.35);if(k.length<5){guide("請讓人物進入畫面");return}const xs=k.map(x=>x.x),ys=k.map(x=>x.y),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),cx=(minX+maxX)/2,h=maxY-minY;ctx.save();ctx.setLineDash([10,8]);ctx.lineWidth=3;ctx.strokeRect(minX-12,minY-12,maxX-minX+24,h+24);ctx.restore();const r=h/overlay.height;if(cx<overlay.width*.42)guide("人物往右一點  →");else if(cx>overlay.width*.58)guide("人物往左一點  ←");else if(r>.88)guide("往後一點  ↓");else if(r<.38)guide("靠近一點  ↑");else guide("✓ 可以拍")}
function capture(){if(!stream||video.readyState<2)return;const c=document.createElement("canvas");c.width=video.videoWidth;c.height=video.videoHeight;const x=c.getContext("2d");if(facingMode==="user"){x.translate(c.width,0);x.scale(-1,1)}x.drawImage(video,0,0,c.width,c.height);c.toBlob(async b=>{if(!b)return;const f=new File([b],"AI攝影師.jpg",{type:"image/jpeg"});try{if(navigator.share&&navigator.canShare?.({files:[f]}))await navigator.share({files:[f],title:"AI 攝影師"});else{const u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="AI攝影師.jpg";a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}}catch(e){}}, "image/jpeg",.92)}
startBtn.onclick=startCamera;shotBtn.onclick=capture;switchBtn.onclick=async()=>{facingMode=facingMode==="environment"?"user":"environment";await startCamera()}
